### ISSUE TITLE
ImportError: cannot import name detector_utils

### ISSUE THREAD

**Issue by ferris1** [victordibia/skyfall#1]
when i run app.py. I get an error！

**ImportError: cannot import name detector_utils**
Is this a version issue?

my version:
tensorflow=1.6.0
Flask==0.12.2
opencv_python==3.4.0.12
numpy==1.14.2
protobuf==3.5.2.post1
websocket_client==0.47.0

**Comment by victordibia** [comment]
Hi,
Looks like your python does not see the files in the `utils` [folder](https://github.com/victordibia/skyfall/tree/master/utils). 

This is a python 2.x thing which gets resolved by adding __init.py__ to the module folder.
I just added __init.py__, you can make a fresh pull request and try again.

> The app has been tested using *Python 3*. Please use your Python 3 environment if possible.

-V
